version: '3.4'

services:
  php:
    image: quay.io/api-platform/php
    build:
      context: .
      target: api_platform_php
      cache_from:
        - quay.io/api-platform/php
        - quay.io/api-platform/nginx
        - quay.io/api-platform/varnish
    depends_on:
      - db
    # Comment out these volumes in production
    volumes:
      - .:/srv/api:rw,cached
      # If you develop on Linux, uncomment the following line to use a bind-mounted host directory instead
      - ./var:/srv/api/var:rw

  api:
    image: quay.io/api-platform/nginx
    build:
      context: .
      target: api_platform_nginx
      cache_from:
        - quay.io/api-platform/php
        - quay.io/api-platform/nginx
        - quay.io/api-platform/varnish
    depends_on:
      - php
    # Comment out this volume in production
    volumes:
      - ./public:/srv/api/public:ro
    ports:
      - 80:80

  db:
    # In production, you may want to use a managed database service
    image: postgres:9.6-alpine
    environment:
      - POSTGRES_DB=api
      - POSTGRES_USER=api
      # You should definitely change the password in production
      - POSTGRES_PASSWORD=!ChangeMe!
    volumes:
      - pg-data:/var/lib/postgresql/data:rw
      # You may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
#      - ./docker/db/data:/var/lib/postgresql/data:rw
    ports:
      - 5431:5432

volumes:
  pg-data: {}
